# Generated by Django 5.1.1 on 2024-10-07 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='outcome',
            field=models.CharField(blank=True, choices=[('white_win', 'White Win'), ('black_win', 'Black Win'), ('draw', 'Draw'), ('white_resigned', 'White Resigned'), ('black_resigned', 'Black Resigned')], max_length=20, null=True),
        ),
    ]
