# Generated by Django 5.1.1 on 2024-10-07 20:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0004_challenge_challenger_notified'),
    ]

    operations = [
        migrations.AddField(
            model_name='challenge',
            name='game',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='game.game'),
        ),
    ]
